apiVersion: v1
kind: Namespace
metadata:
  name: aurelia-finance
  labels:
    tenant: aurelia-finance
    managed-by: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: aurelia-api-secret
  namespace: aurelia-finance
type: Opaque
stringData:
  API_SHARED_TOKEN: CHANGE_ME_AURELIA_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurelia-api
  namespace: aurelia-finance
  labels:
    app: aurelia-api
    tenant: aurelia-finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurelia-api
  template:
    metadata:
      labels:
        app: aurelia-api
        tenant: aurelia-finance
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/"
    spec:
      containers:
        - name: aurelia-api
          image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: LOG_LEVEL
              value: info
            - name: FORWARD_TARGET
              value: http://northstar-api.northstar-logistics.svc.cluster.local
            - name: API_SHARED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aurelia-api-secret
                  key: API_SHARED_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: aurelia-api
  namespace: aurelia-finance
  labels:
    app: aurelia-api
spec:
  selector:
    app: aurelia-api
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aurelia-api
  namespace: aurelia-finance
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: aurelia.orchard.usreliance.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aurelia-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aurelia-default-deny-except-ingress-and-northstar
  namespace: aurelia-finance
spec:
  podSelector:
    matchLabels:
      app: aurelia-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: northstar-logistics
      ports:
        - protocol: TCP
          port: 80
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
